[prune]
  go-tests = true

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  branch = "master"

[[constraint]]
  name = "gopkg.in/olahol/melody.v1"
  version = "1.0.0"

[[override]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.21.0"

[[constraint]]
  branch = "master"
  name = "moul.io/zapgorm"
