[prune]
  go-tests = true

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.5"
  # revision = "071b657418cccdab721e549108b6b6cf8a1b7361"

[[constraint]]
  name = "gopkg.in/olahol/melody.v1"
  version = "1.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.28.0"